### ISSUE TITLE
Tweakwise module cannot be disabled

### ISSUE THREAD

**Issue by bertterheide** [EmicoEcommerce/Magento1Tweakwise#29]
Issue Brief
--
When disabling the Tweakwise Magento module by removing the Tweakwise Key in the admin, the following exception is thrown in the frontend:

> Please provide a valid tweakwise key in System -> Configuration -> Tweakwise -> Key

Environment
--
- [ ] PHP Version: 7.0
- [ ] Magento Version: 1.9.4.0
- [ ] Magento Enterprise: no
- [ ] Tweakwise Version: 1.12.0

Steps to reproduce
--
1. Install Magento from `develop` branch.
2. Install and do not configure the Tweakwise module.
3. Visit the frontend.

Actual result
--
1. An exception is thrown.

Expected result
--
A working shop without exceptions.

**Comment by edwinljacobs** [comment]
This has been released in v1.11.13
