### ISSUE TITLE
Performance issue when rendering rel="nofollow" in attribute template for facets with many attributes

### ISSUE THREAD

**Issue by aadmathijssen** [EmicoEcommerce/Magento1Tweakwise#32]
Issue Brief
--
Performance degradation in `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/attribute.phtml` when rendering `rel="nofollow"` for facets with many attributes

Environment
--
- [x] PHP Version: 7.1
- [x] Magento Version: 1.9.4.0
- [x] Magento Enterprise: no
- [x] Magento1Tweakwise Version: 1.11.12
- [x] Magento Deploy Mode: production

Steps to reproduce
--
1. Take a Magento store with many products, and more than 100 different filter values for one or more facets (typically, "color" or "series").
2. Navigate to a category page or a search result page containing many products.

Actual result
--
Rendering each attribute in the `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/attribute.phtml` template takes multiple milliseconds, resulting in page loads of multiple seconds.

Expected result
--
Rendering each attribute in the `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/attribute.phtml` template takes less than 1 millisecond.

**Comment by edwinljacobs** [comment]
Hi we added some comments to your pull request. We agree with you on the proposed template changes however we are unsure on the changes for Helper/Seo.php.

Could you perhaps review our comments?

**Comment by edwinljacobs** [comment]
Pull has been merged. Closing this issue.
