### ISSUE TITLE
Performance issue when rendering "hidden" class in attribute template for facets with many attributes

### ISSUE THREAD

**Issue by aadmathijssen** [EmicoEcommerce/Magento1Tweakwise#34]
Issue Brief
--
Performance degradation in `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/attribute.phtml` when rendering `hidden` classes for facets with many attributes

Environment
--
- [x] PHP Version: 7.1
- [x] Magento Version: 1.9.4.0
- [x] Magento Enterprise: no
- [x] Magento1Tweakwise Version: 1.11.12
- [x] Magento Deploy Mode: production

Steps to reproduce
--
1. Take a Magento store with many products, and more than 100 different filter values for one or more facets (typically, "color" or "series").
2. Navigate to a category page or a search result page containing many products.

Actual result
--
Rendering the `hidden` class for each attribute in the `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/attribute.phtml` template is slow, taking tens of milliseconds for facets with many attributes.

Expected result
--
The time needed to render the `hidden` class should be negligible.

**Comment by edwinljacobs** [comment]
Hello,

The merge request has been accepted. We took the liberty of optimizing the method
```
public function showMoreText()
```

as well. 
This method relied on the slow method ```isMoreItem``` but is now reimplemented. The method ```isMoreItem``` still exists as it is public and therefor cannot be easily removed.

**Comment by aadmathijssen** [comment]
As a minor remark, it might be better to not use the `showMoreText` method at all and just compare the value of the counter to `$_settings->getNumberOfShownAttributes()`.

Namely, _if_ the method was used inside `app/design/frontend/base/default/template/emico_tweakwise/catalog/layer/facet/tree/items.phtml`, this could have caused an issue, because the logic to decide whether an item should be rendered at all is done in the template itself; the `showMoreText` method does not (and cannot) contain this logic.

**Comment by edwinljacobs** [comment]
The current fix has been released in version 1.11.13
