### ISSUE TITLE
Cannot clear value for the `emico_tweakwise/navigation/nofollow_facets` setting once it has been set

### ISSUE THREAD

**Issue by aadmathijssen** [EmicoEcommerce/Magento1Tweakwise#36]
Issue Brief
--
Whenever one or more values are saved for `emico_tweakwise/navigation/nofollow_facets` system configuration setting, these values cannot be cleared any more.

Environment
--
- [x] PHP Version: 7.1
- [x] Magento Version: 1.9.4.0
- [x] Magento Enterprise: no
- [x] Magento1Tweakwise Version: 1.11.12
- [x] Magento Deploy Mode: production

Steps to reproduce
--
1. Install the plugin.
2. Log in the Magento admin.
3. In the system configuration, go to "Tweakwise" menu.
4. For the "Layered navigation > Attributes which will have a noindex/nofollow" setting, select one or values in the multiselect and click on "Save Config".
5. After the page has been refreshed, deselect all options for the "Layered navigation > Attributes which will have a noindex/nofollow" setting such that none of the options are selected, and click on "Save Config".

Actual result
--
The Tweakwise system configuration page shows a number of selected options for the "Layered navigation > Attributes which will have a noindex/nofollow" setting, namely the ones that were selected in step 4.

Expected result
--
The Tweakwise system configuration page shows no selected options for the "Layered navigation > Attributes which will have a noindex/nofollow" setting.

**Comment by edwinljacobs** [comment]
This has been added and will be released soon

**Comment by edwinljacobs** [comment]
This has been released in v1.11.13
