### ISSUE TITLE
Suggestions are not showing when typing any search term on the search bar (only products)

### ISSUE THREAD

**Issue by julianmurillo** [EmicoEcommerce/Magento1Tweakwise#44]
Environment
--
- [ ] PHP Version: (7.1)
- [ ] Magento Version: 1.9.4.1
- [ ] Magento Enterprise: (no)
- [ ] Tweakwise Export Version: 1.6.3
- [ ] Magento Deploy Mode: (not applicable)

Steps to reproduce
--
1. Type any search term on the search bar.
2. Only products will be shown; no suggestions are shown (even when are they are configured to be shown at System -> Configuration -> Tweakwise -> Search Autocomplete -> Add Suggestions (Yes). Disabling the option 'Add products' would prevent products to show (so this one works well).

Any ideas what could go wrong? What is the main criteria for defining anything as suggestion?

**Comment by edwinljacobs** [comment]
Hi,

I assume that suggestions exist in the navigator (see "Suggesions > Established suggestions")? The template file responsible for rendering the autocomplete results is:
`emico_tweakwise/catalogsearch/autocomplete/result.phtml` this template basically renders all autocomplete results coming from the navigator. It should look like: https://github.com/EmicoEcommerce/Magento1Tweakwise/blob/master/app/design/frontend/base/default/template/emico_tweakwise/catalogsearch/autocomplete/result.phtml

We do not experience this issue with the demo store, see for example: https://tweakwise1-ce.emico.nl/ ans type in 'vase' in the searchbar, it should give a few products but also suggestions.

You could check the navigator and test the suggestions found there. To be honest I am not sure how suggestions are created in the tweakwise navigator, you could ask them.

If the template seems normal (i.e. no 'significant' overrides) and you are convinced that everything should work as expected but doesnt then please add a log entry so we can see whats going on. You can log requests to tweakwise by setting debug to yes in the tweakwise general settings and the log should also be enabled. The requests will be logged to file var/log/tweakwise.log

I noticed  that you are on version 1.6.3, is this the tweakwise-export module or the tweakwise module (the issue template is problably incorrect)? And also, is this version number defined in config.xml? The reason I ask is that the initial release here is on version 1.10.11 which seems like a huge difference. If you do have a very old version consider updating, this will probably solve your problem. 

With kind regards

**Comment by edwinljacobs** [comment]
Is this still an issue?

**Comment by julianmurillo** [comment]
Hi @edwinljacobs the issue has been solved by looking into the established suggestions; thanks for your extensive explanation.

**Comment by edwinljacobs** [comment]
Ok nice! ill close this issue.

With kind regards
