### ISSUE TITLE
Price slider click on bar doesn’t work well.

### ISSUE THREAD

**Issue by EduardSelles** [EmicoEcommerce/Magento1Tweakwise#47]
Issue Brief
--
Dragging the min and max value buttons on the silders works well. But a click halfway through the bar reloads the page, but does not result in a selection of a (the right) value. The same click for the second time gives no response at all.

Environment
--
Magento1 

Steps to reproduce
--
1. goto: https://tweakwise1-ee.emico.nl/men/men-new-arrivals.html 
2. click halfway on the price slider
3. repeat this action

Actual result
1. The max value is selected 
or
2. No response at all

Expected result
1. The right value must be selected (about half the maximum price)

**Comment by edwinljacobs** [comment]
Hi,

Pull: https://github.com/EmicoEcommerce/Magento1Tweakwise/pull/48 is intended to fix this issue.

With kind regards

**Comment by edwinljacobs** [comment]
Hello,

Release v2.0.2 has a fix for this issue.

With kind regards
