### ISSUE TITLE
Active sliders is omitted when using the URL segments Strategy

### ISSUE THREAD

**Issue by stormbyte** [EmicoEcommerce/Magento1Tweakwise#50]
When using the `URL segments Strategy` with slider elements the url params are omitted from the generated url within the `normal` attributes.
Expected result was that if you have a price filter active and add a Brand filter that the active price filter would be carried over to the page.

Environment
--
- [ ] PHP Version: 7.2
- [ ] Magento Version: 1.9.4.2
- [ ] Magento Enterprise: no
- [ ] Magento Deploy Mode: production
- [ ] Ajax enabled: Yes

Steps to reproduce / actual result
--
1. Go to a category page with tweakwise filters, select boxes and sliders
2. Change the slider value ( this value will now be added to the url )
3. Click a selectbox attribute
4. The slider value is now omitted from filtering.

Expected result
--
List the expected results as a bullet list of expectations
- When I activate the price slider and then a Brand filter. I would expect that both a active.

**Comment by edwinljacobs** [comment]
Issue acknowledged.

This will be added to backlog, thanks for the PR (https://github.com/EmicoEcommerce/Magento1Tweakwise/pull/49)

With kind regards

**Comment by edwinljacobs** [comment]
Released in v2.0.3
