### ISSUE TITLE
Improve fallback behaviour when Tweakwise service is not available

### ISSUE THREAD

**Issue by bertterheide** [EmicoEcommerce/Magento1Tweakwise#53]
When, for some reason, the Tweakwise service is not available, defaults are set when parsing the response. These defaults are not coupled to the type that was requested. As an example: in the autocomplete response the suggestions are requested with type none or more, but when the suggestions key does not exist in the response an empty string is set. This is an issue when upgrading to PHP 7.2, as the count method is used more than once on these properties, which triggers warnings.
--
Environment
--
- [ ] PHP Version: 7.2
- [ ] Magento Version: 1.9.3.4
- [ ] Magento Enterprise: no
- [ ] Tweakwise Export Version: 2.3.0
- [ ] Magento Deploy Mode: production
- [ ] Third party modules: n/a

**Comment by edwinljacobs** [comment]
Hello,

If I read this correctly you are saying that in ```app/code/community/Emico/Tweakwise/Model/Bus/Type/Abstract.php``` lines 52 - 56 (here the empty string gets set) should be adjusted to take the ```$count``` variable into account?

We added branch https://github.com/EmicoEcommerce/Magento1Tweakwise/tree/issue/53-defaultvalue-parsing

To address this issue, I havent tested this yet but maybe you can take a look to check if this is indeed what you mean?

**Comment by edwinljacobs** [comment]
Could you check  my previous comment?

**Comment by bertterheide** [comment]
@edwinljacobs haven’t tested this either, but this should fix the issue.

**Comment by edwinljacobs** [comment]
The branch has been merged, the release is soon to follow (I will close this issue afterwards).

With kind regards.

**Comment by edwinljacobs** [comment]
Released in https://github.com/EmicoEcommerce/Magento1Tweakwise/releases/tag/v2.0.5
