### ISSUE TITLE
Layered Navigation URL segments gives 404

### ISSUE THREAD

**Issue by gunneman** [EmicoEcommerce/Magento1Tweakwise#56]
Issue Brief
--
When I activate the URL segments, instead of the query params, I get a 404 error page when selecting any filter.

Environment
--
- [ ] PHP Version: (5.6|7.0|7.1) 7.1
- [ ] Magento Version: 1.9.4.3
- [ ] Magento Enterprise: (yes|no) no
- [ ] Tweakwise Export Version: latest
- [ ] Magento Deploy Mode: (production|development) production
- [ ] Third party modules: Multiple

Steps to reproduce
--
1. In the tweakwise layered navigation configuration select the URL segments and save.
2. Empty al needed caching.
3. Open up category page and select a filter.

Actual result
--
1. Page gives a 404 not found page.

Expected result
--
List the expected results as a bullet list of expectations
- [ ] A category page with the filter applied

**Comment by edwinljacobs** [comment]
Hi,

I dont have this issue on a fresh magento installation with sample data. Could you provide me with some extra details? 

In principle the Router 

https://github.com/EmicoEcommerce/Magento1Tweakwise/blob/ded750b857ef1f8c001a2cdb337dbb8f7c8f4c05/app/code/community/Emico/Tweakwise/Controller/Router.php#L15-L34

should call the following code:

https://github.com/EmicoEcommerce/Magento1Tweakwise/blob/ded750b857ef1f8c001a2cdb337dbb8f7c8f4c05/app/code/community/Emico/Tweakwise/Model/UrlBuilder/Strategy/PathStrategy.php#L238-L257

Can you tell me what happens in these methods (if they are even called)? It would also be good to know if the method getActiveStrategies as called in the Router returns the correct strategies.

WIth kind regards

**Comment by edwinljacobs** [comment]
Closed due to inactivity
